export interface ResearchArea {
  slug: string;
  title: string;
  /** Resumen corto para tarjetas de vista previa (Inicio). */
  summary: string;
}

export interface ResearchSection {
  heading: string;
  paragraphs: string[];
}

/**
 * Las dos líneas de investigación del laboratorio, tal como figuraban en el
 * sitio anterior. El contenido detallado de "Esclero-cronología" viene del
 * documento entregado por el cliente (CONTENIDO CONTEXTO INVESTIGACION.docx).
 *
 * Para "Biología y Ecología de la Reproducción de Peces" el cliente aún no
 * ha entregado un texto descriptivo: se deja pendiente en vez de inventarlo.
 */
export const RESEARCH_AREAS: ResearchArea[] = [
  {
    slug: "esclero-cronologia",
    title: "Esclero-cronología de organismos acuáticos",
    summary:
      "Estudio de los patrones físicos y químicos registrados en bandas de crecimiento de estructuras calcificadas —como otolitos, conchas y exoesqueletos de coral— para reconstruir la historia de vida de organismos acuáticos.",
  },
  {
    slug: "biologia-ecologia-reproduccion",
    title: "Biología y Ecología de la Reproducción de Peces",
    summary:
      "Contenido pendiente de definir por el laboratorio.",
  },
];

/**
 * Desarrollo completo de la línea de Esclero-cronología, para la página
 * de Investigación. Texto tomado casi textual de
 * "CONTENIDO CONTEXTO INVESTIGACION.docx" (solo se omiten un par de
 * rótulos de figura sueltos —p. ej. "Marca de Asentamiento"— que no tienen
 * imagen asociada en este material, y se corrige una palabra duplicada por
 * error de tipeo).
 */
export const ESCLEROCRONOLOGIA_SECTIONS: ResearchSection[] = [
  {
    heading: "¿Qué es la esclero-cronología?",
    paragraphs: [
      "La esclero-cronología estudia los patrones físicos y químicos en bandas de crecimientos temporales registrados en estructuras calcificadas de organismos acuáticos, para reconstruir su historia de vida y su relación con procesos ecológicos, antrópicos y ambientales. La esclero-cronología está orientada principalmente al estudio de los patrones de edad y crecimiento en estructuras calcificadas, tales como exoesqueletos de corales, conchas de moluscos, otolitos, estatolitos, escamas, huesos operculares, vértebras, esqueletos calcáreos, y dientes, entre otras estructuras. No obstante, el registro temporal de propiedades químicas en estas estructuras permite también reconstruir cambios climáticos y ambientales a distintas escalas de espacio y tiempo. Actualmente la esclero-cronología se proyecta como una ciencia interdisciplinaria con aplicaciones diversas, como por ejemplo: (i) reconstrucción de paleoclima, (ii) cambio climático, (iii) aplicaciones a estudios paleo-sísmicos; y (iv) aplicaciones a estudios de manejo y conservación de recursos pesqueros.",
      "La reconstrucción de paleoclima ha sido producto básicamente del desarrollo de la esclero-cronología en corales e invertebrados marinos, fundamentalmente bivalvos. El principio de esta aplicación es que las bandas anuales presentes en fósiles de ambos tipos de organismos registran también marcas isotópicas (14C, δ18O, δ13C), las que pueden ser usadas para reconstruir la circulación del océano, cambios hidrográficos y la dinámica del sistema (Scourse et al., 2006). Hasta la fecha, la mayoría de las aplicaciones utilizando corales han estado restringidas a áreas tropicales, pero el desarrollo de la esclero-cronología en bivalvos proyecta estas aplicaciones a ambientes templados, sub-polares y polares.",
      "Los bivalvos contienen anillos de crecimiento en la región externa e interna de sus conchas calcáreas. Los anillos externos tienen poca utilidad cronológica, debido a que es difícil distinguir los anillos depositados periódicamente de aquellos producidos por alteraciones ambientales (e.g. tormentas severas), además de la dificultad en realizar conteos de los anillos con precisión hacia los bordes de las valvas. Sin embargo, en la última década se han utilizado los anillos internos seccionados con cortadoras de baja. Los anillos internos parecen tener una periodicidad anual (i.e. un ánulo) que está formado por una banda clara y una delgada banda oscura. El anillo oscuro corresponde a los anillos visibles al exterior de las valvas y que son producto de periodos con tasas de calcificación reducidas, debido presumiblemente a una gran variedad de factores, entre los cuales podemos mencionar inviernos fríos, veranos cálidos, y/o ciclos de desove. Recientemente varios estudios han utilizado bivalvos de gran longevidad como archivos marinos de alta resolución. Un caso particular es la especie Arctica islandica, que puede vivir entre 3 y 4 siglos y que ha permitido reconstruir la circulación oceánica en el Atlántico noroeste (Schöne et al., 2005; Wanamaker et al., 2008), así como también patrones de productividad secundaria en función de variables ambientales (Witbaard et al., 2003).",
    ],
  },
  {
    heading: "¿Qué es la esclero-cronología basada en otolitos?",
    paragraphs: [
      "Los otolitos de peces han sido los más usados en estudios esclero-cronológicos. Estas estructuras calcificadas se encuentran en el oído interno de peces óseos, y su función es actuar como receptor mecánico de las señales transmitidas por el nervio auditivo, a fin de mantener el balance del pez en el medio acuático. El otolito crece por deposición de capas concéntricas (denominadas anillos de crecimiento) de carbonato de calcio y proteínas, las cuales son depositadas a intervalos regulares que pueden ser diarios o estacionales. Los anillos de crecimiento estacionales están formados a su vez por una zona translúcida y otra opaca, constituyendo entre ambas un anillo anual (denominado ánulo), cuyo crecimiento registra la cronología histórica desde el nacimiento hasta la fecha de muerte del pez. Alternativamente, los anillos de crecimiento diario (o micro-incrementos, Panella 1971) son solamente visibles a través de un microscopio durante el primer año de vida del pez, debido a que su crecimiento es mayor durante dicho periodo.",
      "Hasta la fecha varios estudios han demostrado la extraordinaria capacidad que tienen los otolitos para registrar información en su micro y macro estructura. Así por ejemplo, edad, crecimiento, patrones de movimientos, y/o interacción de hábitat son registrados a diferentes escalas temporales. Dicha información puede ser interpretada a nivel poblacional en términos de ecología, demografía y/o historia de vida de una especie dada, con el fin de asegurar su manejo y conservación. Más específicamente, la estructura de los micro incrementos, además de registrar la edad y crecimiento diario, también registra transiciones ontogenéticas que ocurren durante las fases tempranas de su desarrollo, tornándose en una herramienta potencial para estudios ecológicos de peces marinos y dulceacuícolas. En adición, recientemente ha emergido una nueva sub-disciplina basada en la microquímica de los otolitos. Dicha área está basada en el principio de que el otolito, al ser metabólicamente inerte (i.e., su material no es reabsorbido) y crecer continuamente a través de la vida del pez, mantiene la composición química del ambiente al cual el pez estuvo expuesto (Campana, 1999). Entre las aplicaciones de la microquímica de los otolitos están su efectividad como marcadores naturales de áreas natales o de crianza, identificación de stocks, migraciones, y/o detección de anadromía, entre otras.",
    ],
  },
  {
    heading:
      "Aplicaciones del análisis de otolitos en el estudio de la historia de vida en los estadios tempranos de peces",
    paragraphs: [
      "En muchas especies de peces marinos la micro-estructura de sus otolitos no ha sido descrita, que es el caso de la mayoría de los peces chilenos. Para estas especies, la primera etapa es analizar la micro-estructura para larvas y juveniles con el objeto de evaluar qué tipo de información ecológica el otolito contiene. Indudablemente, información básica sobre edad y crecimiento puede ser obtenida para cualquier especie analizada. En el caso de peces demersales, es necesario evaluar si existen marcas en la micro-estructura de los otolitos (e.g., cambios bruscos en el ancho de los micro-incrementos, presencia de áreas con cambios en resolución, y/o marcas en las que la deposición de carbonato de calcio se pudo haber interrumpido o alterado) que puedan estar asociadas con el cambio de modo de vida desde el ambiente pelágico al bentónico. Si este es el caso, el número de micro-incrementos diarios depositados a partir del periodo de transición puede ser sustraído de la fecha de captura, para estimar los patrones de asentamiento con extraordinaria exactitud. Del mismo modo, el número de micro-incrementos formados a partir de la eclosión hasta la zona de transición es un estimador preciso de la fase planctónica. Tal como en el caso de peces demersales, los movimientos ontogenéticos desde el ambiente pelágico hacia aguas someras de crianza, durante la fase juvenil de varios peces estuarios y litorales, pueden también ser potencialmente registrados en la estructura de sus otolitos. Consecuentemente, los patrones temporales de migración y su relación con variables ambientales (e.g. corrientes mareales, fases lunares, procesos de surgencia costera, corrientes inducidas por viento, etc.) pueden ser evaluados. Un objetivo alternativo en este tipo de estudios exploratorios es la validación de la periodicidad diaria de los micro-incrementos para la especie en cuestión. La validación puede llevarse a cabo a través de métodos de marcaje de otolitos en individuos tratados en condiciones experimentales. El método de marcaje de otolitos más comúnmente usado es por inmersión de individuos en una solución de tetraciclina, la cual produce una marca fluorescente en el otolito.",
      "La esclero-cronología a nivel diario en peces juveniles es la que menos se ha desarrollado, quizás debido a dos causas fundamentales: (i) el hecho de que los juveniles son menos vulnerables a los muestreos ictioplanctónicos y comerciales, dificultando cualquier diseño de muestreo y planes de investigación, y (ii) el hecho de que los otolitos deben ser pulidos manualmente en un proceso que requiere tiempo y entrenamiento (e.g., algunos juveniles pueden tener secuencias de más de 200 micro-incrementos). Más aún, cada especie tiene su propia resolución, lo cual hace de su lectura un proceso de interpretación especializado. Por este motivo, el estudio exploratorio de otolitos de juveniles debe ser un proceso continuo, incorporando nuevas especies siempre que sea posible.",
    ],
  },
  {
    heading: "Crecimiento y sobrevivencia durante las fases tempranas de peces marinos",
    paragraphs: [
      "Uno de los grandes paradigmas en el estudio de la ecología y biología de peces marinos es el hecho de que existe gran variabilidad en la sobrevivencia durante los estadios tempranos de su ciclo de vida, la cual está relacionada con la variabilidad en el reclutamiento. Este último es determinante de la fuerza de la clase anual y, por lo tanto, del tamaño de una población explotable. En consecuencia, existe un gran interés científico y económico por identificar los factores y condiciones que influyen en el reclutamiento durante las fases larvarias y juveniles tempranas. En este sentido, estudios recientes han sugerido que existe una conexión entre crecimiento y mortalidad, la cual puede explicar la supervivencia de los estadios tempranos de peces teleósteos. Esta hipótesis sugiere que el crecimiento opera bajo la acción de tres mecanismos, los cuales no son necesariamente mutuamente exclusivos, pero que hacen del crecimiento un factor covariante en determinar la supervivencia de la descendencia. El primero de estos mecanismos sugiere que si la mortalidad decrece funcionalmente con el tamaño del pez, entonces aquellos individuos más grandes a cualquier edad definida tendrían menor probabilidad de mortalidad que aquellos más pequeños (i.e., bigger is better mechanism; Leggett and DeBlois, 1994). El segundo establece que si la mortalidad es tamaño-dependiente, entonces las tasas de crecimiento mayores podrían reducir el tiempo en el cual los individuos experimentan elevadas tasas de mortalidad. En otras palabras, una cohorte que exhibe tasas de crecimiento lentas —como resultado, por ejemplo, de una baja disponibilidad de alimento, o por efecto de variables ambientales desfavorables— puede tener un período larvario prolongado y una mortalidad acumulativa muy alta. En contraste, los individuos de una cohorte que crecen rápidamente tienen un período larvario más corto y, por ende, una menor mortalidad acumulativa. Consecuentemente, aquellos individuos que crecen rápidamente tienen una mayor probabilidad de sobrevivir (i.e., growth-rate mechanism; Shepherd and Cushing, 1980; Houde 1997). El tercer mecanismo sugiere que aquellos individuos que hacen las transiciones ontogenéticas (e.g., saco vitelino a primera alimentación, larva a juvenil) a edades más tempranas tienen una mayor probabilidad de sobrevivir, y viceversa (i.e., \"stage duration\" mechanism; Houde, 1997). A pesar de que varios estudios han evidenciado una relación conspicua entre crecimiento y mortalidad para un número de especies, pruebas fehacientes de la operatividad de los tres mecanismos descritos han sido escasamente proporcionadas.",
      "Los tres mecanismos descritos pueden ser evaluados en una especie que presente una suficiente resolución en la formación de sus micro-incrementos. El principio es sencillo: el ancho de los micro-incrementos previamente formados a una edad (i) permanece intacto debido a la estructura inerte y crecimiento continuo del otolito. Por lo tanto, al comparar el ancho del incremento (como un indicador del crecimiento diario) a una edad previa (i) usando otolitos de larvas planctónicas, con el ancho del incremento a la misma edad (i) usando otolitos de individuos colectados en estados más avanzados de desarrollo (e.g. 0+ juveniles), es posible inferir si el crecimiento fue mayor, similar, o inferior en los sobrevivientes de una misma población.",
    ],
  },
  {
    heading: "Aplicaciones del análisis de otolitos en identificación de stock",
    paragraphs: [
      "El concepto de stock en ciencia pesquera ha sido históricamente definido de diferentes maneras (Waldman, 1999), siendo las más comunes la definición genética y la operacional. La primera se define como unidad reproductivamente aislada, la cual es genéticamente diferente de otros stocks. La segunda responde a una definición más reciente que establece que un stock es \"un grupo semi-discreto de peces con algunos atributos característicos que son de interés para la administración pesquera\", previa a la fijación de cuotas de captura de manera de asegurar la sustentabilidad de un determinado recurso en el tiempo (Begg et al., 1996). Dicha definición responde al estado del arte actual, que sugiere que la estructura poblacional de una especie dada es mucho más compleja y dinámica de lo que se pensaba, en la que intervienen no solo factores genéticos sino también medioambientales, y en la que parámetros clave para la sustentabilidad del recurso, como crecimiento, fecundidad y mortalidad, aparecen homogéneos (Gauldie, 1988). En el ámbito pesquero se considera generalmente la existencia de un stock si el 90% del recurso se renueva a partir de los adultos presentes en la zona, es decir, que un 10% del reclutamiento proviene de migraciones desde otras zonas. Un intercambio de pocos individuos por generación entre sitios lejanos basta para homogeneizar la composición genética de la especie (Hauser & Ward, 1998; Ojeda et al., 2002).",
      "La identificación de stock se ha abordado a través de diversas disciplinas y/o metodologías, tales como (i) merística, (ii) patrones en la historia de vida, (iii) carga parasitaria, y más recientemente (iv) otolimetría, (v) ácidos grasos y (vi) genética de poblaciones. La aplicación de la merística clásica ha demostrado ser de utilidad en un número de especies (Junquera y Gandaras, 1993; Bowering et al., 1998), la que se ha fortalecido por el reciente desarrollo de la morfometría geométrica, técnica robusta en la descripción e interpretación de patrones de variación más allá del nivel especie-específico (Cadrin, 2000; Murta, 2000). Los patrones en la historia de vida pueden alcanzar un nivel de discriminación cuando existen poblaciones con periodos y zonas de desove discretos y bien definidos, y otorgan información útil para describir la estructura de stock desde un sentido operacional, de mucha utilidad al compararse con métodos de mayor resolución. La carga parasitaria puede proveer información relacionada con los patrones de distribución biogeográfica del huésped y, cuando existe información sobre los ciclos de vida de los parásitos identificados, ha demostrado ser una herramienta robusta para identificar stock y migraciones de recursos acuáticos (Mackenzie, 1987; Williams et al., 1992); hasta la fecha, los parásitos más comúnmente usados en peces marinos han sido las larvas de nematodos anisakis (Smith & Wootten, 1978; Mackenzie, 1987).",
      "El análisis de otolitos ofrece dos herramientas alternativas para la identificación de stock de peces: (a) el análisis de la morfología y (b) la microquímica de los otolitos. La primera se basa en el hecho de que la morfología de los otolitos es altamente especie-específica e incluso puede variar entre sub-poblaciones o unidades de stock. En sus inicios, esta técnica solo incluyó parámetros morfológicos relacionados con la dimensión de los otolitos, que ofrecieron un buen nivel de resolución para la identificación de stock en ciertas especies. En la última década, sin embargo, la disponibilidad de nuevas herramientas de análisis de imágenes y algoritmos estadísticos de clasificación ha mejorado la robustez discriminatoria de esta herramienta. Por su parte, la microquímica está basada en el principio de que el otolito, al ser metabólicamente inerte y crecer continuamente a través de la vida del pez, mantiene la composición química del ambiente al cual el pez estuvo expuesto (Campana, 1999), y por consiguiente ha demostrado ser una herramienta eficiente para identificar stock en varias especies (Edmonds et al., 1989, 1991, 1992; Campana and Gagne, 1995; Campana et al., 1995; Bickford and Hannigan, 1990; Kalish, 1990).",
    ],
  },
];
